version: "3.8"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file: ./api/.env
    volumes:
      - ./api:/app  
    networks:
      - real-state-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file: ./client/.env
    volumes:
      - ./client:/app   
    networks:
      - real-state-network

networks:
  real-state-network:
    driver: bridge